apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: hellors
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: myapp
          image: gcr.io/google-samples/hello-app:1.0
